package dev.niels.skidbladnir

// GENERATED BY scripts/gen-ornament — DO NOT EDIT (drift-gated by scripts/check-ornament)
//
// Frozen ornament geometry (design-language.md §7 §8, ornament-pipeline.md).
// Every List<OrnamentSegment> below is monoline stroke data in a unit box;
// topology is computed on-device — the app only draws these constants.

internal data class OrnamentSegment(val x1: Float, val y1: Float, val x2: Float, val y2: Float)

// One chevron unit (design-language.md §7): 45° turns only, unit box aspect
// 1:1. Tiles horizontally with no seam — every copy starts and ends at y=1.
internal val FretCell: List<OrnamentSegment> = listOf(
    OrnamentSegment(0f, 1f, 0.5f, 0f),
    OrnamentSegment(0.5f, 0f, 1f, 1f),
)

// The tricursal valknut (design-language.md §8): three interlocked
// equilateral triangles, Borromean topology, straight lines only, unit box
// aspect 1:1. All six over/under crossings are baked as gaps.
internal val Valknut: List<OrnamentSegment> = listOf(
    OrnamentSegment(0.364125f, 0.043864f, 0.086771f, 0.524255f),
    OrnamentSegment(0.086771f, 0.524255f, 0.430253f, 0.524255f),
    OrnamentSegment(0.485724f, 0.524255f, 0.514276f, 0.524255f),
    OrnamentSegment(0.569747f, 0.524255f, 0.641479f, 0.524255f),
    OrnamentSegment(0.641479f, 0.524255f, 0.364125f, 0.043864f),
    OrnamentSegment(0.172912f, 0.845739f, 0.72762f, 0.845739f),
    OrnamentSegment(0.72762f, 0.845739f, 0.513868f, 0.475509f),
    OrnamentSegment(0.486132f, 0.42747f, 0.450266f, 0.365348f),
    OrnamentSegment(0.450266f, 0.365348f, 0.372389f, 0.500236f),
    OrnamentSegment(0.344653f, 0.548275f, 0.172912f, 0.845739f),
    OrnamentSegment(0.962963f, 0.610397f, 0.685609f, 0.130005f),
    OrnamentSegment(0.685609f, 0.130005f, 0.563601f, 0.341329f),
    OrnamentSegment(0.535866f, 0.389368f, 0.408255f, 0.610397f),
    OrnamentSegment(0.408255f, 0.610397f, 0.56401f, 0.610397f),
    OrnamentSegment(0.61948f, 0.610397f, 0.962963f, 0.610397f),
)
