#!/bin/sh
set -eu
[ -n "${TMUX_PANE:-}" ] || exit 0
case "$TMUX_PANE" in
  % | %*[!0-9]* | [!%]*) exit 0 ;;
esac
/usr/bin/tmux set-option -p -t "$TMUX_PANE" @skid_attention "$(/usr/bin/date +%s)"
printf '\a' >"$(/usr/bin/tmux display-message -p -t "$TMUX_PANE" '#{pane_tty}')"
